# 종목명, 현재가격, 거래량
## 데이터프레임 제작, csv저장

In [2]:
import requests as req
from bs4 import BeautifulSoup as bs

In [4]:
res = req.get("https://finance.naver.com/sise/sise_quant.naver")

In [40]:
soup = bs(res.text,"lxml")
co = soup.select('a.tltle')
num = soup.select('td.number:nth-child(3)')
tv = soup.select('td.number:nth-child(6)')

In [41]:

for i in co:
    print(i.text)
for i in num:
    print(i.text)
for i in tv:
    print(i.text)

KODEX 200선물인버스2X
KODEX 코스닥150선물인버스
SH에너지화학
현대약품
KODEX 인버스
KODEX 레버리지
국동
GS글로벌
KODEX 코스닥150레버리지
아남전자
TIGER 차이나전기차SOLACTIVE
일동제약
삼성 인버스 2X WTI원유 선물 ETN
대한전선
TIGER 200선물인버스2X
삼성전자
사조동아원
쌍방울
삼부토건
고려산업
까뮤이앤씨
DB하이텍
대성에너지
신한 인버스 2X 천연가스 선물 ETN
TRUE 인버스 2X 천연가스 선물 ETN(H)
KODEX 코스닥150
부산주공
후성
삼성중공업
KODEX 200
NPC
두산에너빌리티
에이프로젠 MED
팬오션
KODEX WTI원유선물인버스(H)
KBSTAR KIS단기종합채권(AA-이상)액티브
LG디스플레이
KEC
일동홀딩스
국제약품
서울식품
신한 인버스 2X WTI원유 선물 ETN(H)
신일전자
TYM
SK하이닉스
대한제당
SK바이오사이언스
대원화성
와이투솔루션
TIGER 원유선물인버스(H)
대한항공
KODEX 은행
써니전자
한창
대호에이엘
HMM
부광약품
KODEX 2차전지산업
광명전기
미래에셋증권
하나금융지주
일진홀딩스
에스디바이오센서
우리금융지주
한신기계
대성산업
TIGER 2차전지테마
한국토지신탁
카카오뱅크
SG세계물산
진흥기업
TIGER 코스닥150선물인버스
신성이엔지
TIGER KEDI혁신기업ESG30
수산중공업
동양철관
카카오
진원생명과학
KODEX 미국달러선물인버스2X
신한 인버스 2X 천연가스 선물 ETN(H)
신송홀딩스
대원제약
삼성 블룸버그 인버스 2X WTI원유 선물 ETN
한화투자증권
대한해운
남선알미늄
KG스틸
기아
제이알글로벌리츠
TIGER 인버스
이연제약
한국항공우주
한화생명
TIGER 미국필라델피아반도체나스닥
신한지주
신풍제약
QV 인버스 레버리지 WTI원유 선물 ETN(H)
에어부산
모나미
SK증권
3,390
5,265
1,050
6,360
5,070
13,960
2,085
3,505
7,845
2,500
16,580
41,450
120
1,765
3,550
58,100
1,520
549
2,180
6,770
2,245
41,750
11,350
355
645
10,600
822
16,100
5,360
30,535
9,030
17,900
1,605
5,190
4,320
100,790
14,550
2,505
31,850
5,920
251
110
2,080
2,390
92,900
3,270
146,500
2,810
762
3,005
23,500
5,910
2,695
908
2,360
23,550
8,930
16,695
2,960
6,140
35,800
6,380
48,300
11,400
8,820
5,070
16,835
1,605
29,900
542
1,615
5,385
1,830
8,685
3,000
1,055
69,800
11,650
7,125
215
11,850
18,900
17,290
3,025
2,325
2,060
12,300
78,200
4,375
5,650
26,050
47,850
2,095
8,920
35,600
25,950
100
1,360
3,635
712
111,064,162
31,476,157
25,131,657
19,328,242
18,897,243
17,055,001
11,492,024
9,978,498
9,411,020
9,193,725
7,770,772
7,265,289
6,899,250
6,079,904
5,998,303
5,943,165
4,156,077
3,442,318
3,440,602
3,372,720
3,255,870
2,834,387
2,714,084
2,424,284
2,394,990
2,303,047
2,247,651
2,209,341
2,111,131
2,054,294
2,045,746
1,958,504
1,910,080
1,808,692
1,644,830
1,616,444
1,603,653
1,527,918
1,496,733
1,488,146
1,431,555
1,354,809
1,337,705
1,322,377
1,264,197
1,223,491
1,182,489
1,149,506
1,109,858
1,105,106
1,088,655
1,085,260
1,044,038
1,032,824
998,634
967,384
942,571
932,805
911,692
894,214
893,010
873,776
855,688
854,155
853,923
846,101
825,935
814,835
796,828
781,267
776,283
768,024
765,787
753,970
739,797
731,386
712,248
691,519
687,695
687,339
683,072
666,404
656,572
656,266
645,956
640,238
639,955
630,860
628,697
606,750
601,804
599,553
599,139
593,631
585,758
582,534
577,278
572,037
547,441
540,541

In [42]:
eventName = []
pricing = []
tradingVolume = []
for i in range(len(co)):
    eventName.append(co[i].text)
    pricing.append(num[i].text)
    tradingVolume.append(tv[i].text)

In [43]:
import pandas as pd

In [51]:
dic = {"종목명" : eventName, "가격정보" : pricing, "거래량":tradingVolume}
kospi = pd.DataFrame(dic)
kospi

                            종목명    가격정보          거래량
0              KODEX 200선물인버스2X   3,390  111,064,162
1             KODEX 코스닥150선물인버스   5,265   31,476,157
2                       SH에너지화학   1,050   25,131,657
3                          현대약품   6,360   19,328,242
4                     KODEX 인버스   5,070   18,897,243
..                          ...     ...          ...
95                         신풍제약  25,950      582,534
96  QV 인버스 레버리지 WTI원유 선물 ETN(H)     100      577,278
97                         에어부산   1,360      572,037
98                          모나미   3,635      547,441
99                         SK증권     712      540,541

[100 rows x 3 columns]

In [46]:
kospi.to_csv("코스피.csv", encoding="euc-kr")